### ISSUE TITLE
[Showcase] Showcase page draft

### ISSUE THREAD

**Issue by nikoloza** [vigour-io/uikit#1]
Please share your opinion about the design draft I'm working on:

Colors page:
![desktop hd](https://cloud.githubusercontent.com/assets/962224/10938420/62322fd2-82fa-11e5-9990-1a9207a93944.jpg)

Typography page:
![desktop hd 2](https://cloud.githubusercontent.com/assets/962224/10938435/82d98924-82fa-11e5-87d0-640b610c6894.jpg)

That's overall style for UI Kit showcase page. Please fell free to judge it in any case, will be nice to improve.

In case of confirmation by you guys, I'll translate it to markup and continue working on fly.

@youzi @jimdebeer @gideonvd

**Comment by nikoloza** [comment]
I'm trying to mention more guys, I'm just unable to do it :confused: 

The sketchfile:
http://c.nikoloz.me/1q1n3Z0K2z0F
It's little bit dirty although, just for better view :)

**Comment by gideonvd** [comment]
Hi Nika,

Great start, well done! Let's take some time on Friday to align this with current colours and the prototype.

**Comment by nikoloza** [comment]
Hi @gideonvd 

Sure, it'll be very nice

**Comment by jimdebeer** [comment]
@nikoloza this is a nice-to-have just focus on the list for the implementations first I geuss

**Comment by jimdebeer** [comment]
#2 <--- this one first!
