### ISSUE TITLE
[Components] Elements needed for next week

### ISSUE THREAD

**Issue by nikoloza** [vigour-io/uikit#2]
- [x] input
- [x] icon
- [x] notification
  - [x] desktop
- [x] dropdown

![image](https://cloud.githubusercontent.com/assets/962224/11042167/e60a6d82-8715-11e5-9c9f-e17022082377.png)
usable like this sort of (nicer)
- [x] line item 
  - [x] icon , subtitle, title
  - [x]  title, subtitle
  - [x] input + icon
  - [x] dropdown (make it nice!)
  - [x] switch on/off button

**Comment by jimdebeer** [comment]
@nikoloza status on this issue? Looks like icon is the only thing finished...

**Comment by nikoloza** [comment]
@jimdebeer hey jim, as I fix scroll issue, all of this will be done in one hour, because I have setup for each one already.

**Comment by nikoloza** [comment]
done, please check mtv showcase for more
