### ISSUE TITLE
[Clean] Clean up UIkit

### ISSUE THREAD

**Issue by youzi** [vigour-io/uikit#24]
https://github.com/vigour-io/play/issues/66. A lot of these issues can also be found in uikit.

I would suggest to:
- inject css and text on Element by default in uikit.
- make a "UIElement" class which has the special uikit/lib/property injected

**Comment by nikoloza** [comment]
@youzi, Can we inject `css`, `text` and that special property for all `uikit` components somewhere once? that'd be pretty cool indeed.
